/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Apr 18 23:17:14 2018. */

#include "Temperature.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Temperature_fields[3] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, Temperature, notify, notify, &Notify_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, Temperature, config, notify, &Config_fields),
    PB_LAST_FIELD
};

const pb_field_t Notify_fields[4] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, Notify, current, current, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Notify, heatingState, current, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Notify, coolingState, heatingState, 0),
    PB_LAST_FIELD
};

const pb_field_t Config_fields[4] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, Config, target, target, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, Config, gisteris, target, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, Config, tuningSensor, gisteris, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Temperature, notify) < 65536 && pb_membersize(Temperature, config) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Temperature_Notify_Config)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Temperature, notify) < 256 && pb_membersize(Temperature, config) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Temperature_Notify_Config)
#endif


/* @@protoc_insertion_point(eof) */
