
spring:
 jmx.enabled: false
 datasource:
    driver-class-name: org.postgresql.Driver
    type: org.postgresql.ds.PGPoolingDataSource
    url: jdbc:postgresql://localhost:5432/datalogger
    username: datalogger
    password: datalogger
server:
    port: 8080

management.endpoints.web.exposure.include: metrics, info, health
management.metrics.export.simple.enabled: true
#management.metrics.enable: true
management.metrics.enable.example.remote: true


logging:
 file: ./logs/datalogger.log
 level:
  io.netty.handler: WARN
  org.springframework.web: INFO
  org.springframework.security: WARN
  org.postgresql.jdbc: WARN
  org.springframework.jdbc: WARN

---

spring:
  profiles: prod
  datasource:
      url: jdbc:postgresql://localhost:5432/datalogger
      username:
      password: